# This is a basic workflow to help you get started with Actions

name: Server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main, master]
    paths:
      - 'functions/**'
      - '.github/workflows/server.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}-server
      cancel-in-progress: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            functions/node_modules
          key: server-${{ runner.os }} # Key is generic as for frequent package updates

      - name: Install Dependencies
        working-directory: functions
        run: npm install

      - name: Lint code
        working-directory: functions
        run: npm run lint

      - name: Test code
        working-directory: functions
        run: npm run test:ci

      - name: Deploy Cloud Functions
        working-directory: functions
        run: firebase deploy --only functions:translate --token "${{ secrets.FIREBASE_TOKEN }}"
