# This is a basic workflow to help you get started with Actions

name: Server

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - 'functions/**'
      - '.github/workflows/server.yml'


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            functions/node_modules
          key: server-${{ runner.os }}-${{ hashFiles('functions/package.json') }}

      - name: Install Dependencies
        working-directory: functions
        run: npm install
      #
      #      - name: Lint code
      #        run: npm run lint
      #
      #      - name: Test code
      #        run: npm run test:ci
      #
      #      - name: Coveralls
      #        uses: coverallsapp/github-action@master
      #        with:
      #          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Service Account Key
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SIGN_MT }}" > $HOME/gcloud.json

      - name: Deploy Cloud Functions
        working-directory: functions
        run: export GOOGLE_APPLICATION_CREDENTIALS="$HOME/gcloud.json" && npm run deploy
